# Generated by Django 4.2.16 on 2024-10-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nommbre')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Titulo')),
                ('publication_date', models.DateField(verbose_name='Fecha de Publicacion')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.author', verbose_name='Autor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
